baseURL: '/'
languageCode: 'en-us'
title: 'Sociology J'

theme: ['hugo-embed-pdf-shortcode', 'hugo-book']



params:
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme: "auto"
  BookMenuBundle: "/menu"
  BookLogo: "booklogo.png"
