baseURL: '/'
#languageCode: 'en-us'
title: 'Sociology J'

theme: ['hugo-book', 'hugo-embed-pdf-shortcode']




params:
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme: "auto"
  BookMenuBundle: "/menu"
  BookLogo: "booklogo.png"


defaultContentLanguage: kr
defaultContentLanguageInSubdir: true
languages:
  cn:
    contentDir: content/cn
    disabled: false
    languageCode: zh-CN
    languageDirection: ltr
    languageName: Chinese
    params:
      subtitle: 社会学知识
    title: Sociology J
    weight: 1
  kr:
    contentDir: content/kr
    disabled: false
    languageCode: ko-KR
    languageDirection: ltr
    languageName: Korean
    params:
      subtitle: Knowledge of Sociology
    title: Sociology J
    weight: 2