baseURL: 'http://sociology.jmsu.me/'
languageCode: 'en-us'
title: 'Sociology J'


params:
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme: "auto"
  BookMenuBundle: "/menu"
  BookLogo: "booklogo.png"
